"""Remove category.name foreign keys

Revision ID: 3378f8b3ad67
Revises: 7a6b43635076
Create Date: 2020-05-30 20:52:18.207671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3378f8b3ad67'
down_revision = '7a6b43635076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_category_name_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'category_name')
    op.drop_constraint('shop_category_name_fkey', 'shop', type_='foreignkey')
    op.drop_column('shop', 'category_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('shop_category_name_fkey', 'shop', 'category', ['category_name'], ['name'])
    op.add_column('item', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('item_category_name_fkey', 'item', 'category', ['category_name'], ['name'])
    # ### end Alembic commands ###
