"""Initial migration.

Revision ID: 7a6b43635076
Revises: 
Create Date: 2020-05-30 20:49:44.083762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6b43635076'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probe_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('macaddress', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('ssid', sa.String(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('probe_requests')
    # ### end Alembic commands ###
