"""empty message

Revision ID: b598729d56e5
Revises: 3378f8b3ad67
Create Date: 2020-08-04 10:53:30.375496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b598729d56e5'
down_revision = '3378f8b3ad67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probe_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('macaddress', sa.String(), nullable=True),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('ssid', sa.String(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('association')
    op.drop_table('list')
    op.add_column('liste', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'liste', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'liste', type_='foreignkey')
    op.drop_column('liste', 'user_id')
    op.create_table('association',
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='association_item_id_fkey'),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], name='association_list_id_fkey')
    )
    op.create_table('list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='list_category_id_fkey'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name='list_shop_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='list_pkey')
    )
    op.drop_table('probe_requests')
    # ### end Alembic commands ###
