"""Remove amount colum from Item

Revision ID: bf5239e5b5e2
Revises: 
Create Date: 2020-07-14 17:25:24.148716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5239e5b5e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_unique_item_uc', 'item', type_='unique')
    op.create_unique_constraint('_unique_item_uc', 'item', ['name', 'price', 'volume', 'price_per_volume', 'sale', 'note'])
    op.drop_column('item', 'amount')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('_unique_item_uc', 'item', type_='unique')
    op.create_unique_constraint('_unique_item_uc', 'item', ['name', 'price', 'volume', 'price_per_volume', 'sale', 'note', 'amount'])
    # ### end Alembic commands ###


def upgrade_probe_request():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_probe_request():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

